In [14]:
import pandas as pd

In [15]:
dataset = pd.read_csv('../data/direct_marketing.csv')

In [16]:
dataset.head()

,ID,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
0,100,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
1,101,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,11
2,102,7,2) $100 - $200,180.65,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0,1
3,103,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0,2
4,104,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,4

In [17]:
dataset = dataset.drop(['conversion', 'spend'], axis=1)

In [18]:
dataset.head()

,ID,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,DM_category
0,100,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,4
1,101,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,11
2,102,7,2) $100 - $200,180.65,0,1,Surburban,1,Web,Womens E-Mail,0,1
3,103,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,2
4,104,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,4

In [19]:
data = dataset.sample(frac=0.95, random_state=786).reset_index(drop=True)
data_unseen = dataset.drop(data.index).reset_index(drop=True)
new_customers = data_unseen.drop(['visit'], axis=1)
print('Data for Modeling: ' + str(data.shape))
print('Unseen Data for Predictions: ' + str(data_unseen.shape))

Data for Modeling: (60800, 12)
Unseen Data for Predictions: (3200, 12)

In [20]:
new_customers.to_csv(r'../data/new_customers.csv', index=False, header=True)

In [21]:
from pycaret.classification import *
clf = setup(data, target='visit', session_id=562, ignore_features=['ID'], silent=True)

Setup Succesfully Completed!

In [22]:
nb = create_model('nb')

In [23]:
nb_final = finalize_model(nb)

In [24]:
save_model(nb_final, '../final_models/nb_direct')

Transformation Pipeline and Model Succesfully Saved